language: java
jdk:
  - oraclejdk8
branches:
  only:
    - master
    - develop
notifications:
  email: true
  on_success: always
  on_failure: always
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - MCC_FETCH_USER=myMavenRepo
    - MCC_FETCH_PASSWORD=mrcraftcod
