language: java
install: "mvn -U clean install -DskipTests=true -B"
jdk:
  - oraclejdk8
branches:		
  only:		
    - master		
    - development
    - develop
notifications:
  email: true
  on_success: always
  on_failure: always
cache:
  directories:
    - $HOME/.m2
