language: java
install: "mvn -U clean install -DskipTests=true -B"
after_success:
  - bash <(curl -s https://codecov.io/bash)
jdk:
  - oraclejdk8
branches:		
  only:		
    - master		
    - development
    - develop
notifications:
  email: true
  on_success: always
  on_failure: always